# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      for (( i = 0; [$? != 0] && [$i < 10]; i++ ));
      do
        # Echoes in Red
        echo "Waiting 1 minute and trying again..."
        sleep 1m
        func azure functionapp publish tonypythonfunc --python
      done

      if [[ $? != 0 ]]
      then
        echo "Too many failures while trying to deploy $app"
        exit 1
      fi
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: CmdLine@2
  inputs:
    script: 'az login --service-principal --username "7efc50cc-f18d-402b-bcf3-5f5dd3f4197d" --password "3d.A1w_bzOwPF7x~JL~18XZOK~Qb..84.f" --tenant "e4c9ab4e-bd27-40d5-8459-230ba2a757fb"'
- task: CmdLine@2
  inputs:
    script: 'sudo apt-get install azure-functions-core-tools-3'
- task: CmdLine@2
  inputs:
    script: 'func azure functionapp publish tonypythonfunc --python'
  

      